name: 'Install UBI'
description: 'Install IBM UBI tool'

inputs:
  version:
    description: 'UBI version to install (e.g. v0.0.36 or "latest")'
    required: false
    default: 'latest'

  install-path:
    description: 'Directory for the UBI binary'
    required: false
    default: '/usr/local/bin'

  sudo:
    description: 'Install with sudo'
    required: false
    default: 'false'

outputs:
  ubi-path:
    description: 'Full path to the installed UBI binary'

runs:
  using: 'composite'
  steps:
    - run: ./entrypoint.sh
      shell: bash

branding:
  icon: 'package'
  color: 'blue'
