---
name: 'Install ubi (Universal Binary Installer)'
description: 'Installs ubi, a tool for installing pre-built binaries'
author: 'Your Name'

branding:
  icon: 'download'
  color: 'blue'

# No inputs needed - the bootstrap script handles everything automatically

outputs:
  version:
    description: 'The version of ubi that was installed'
    value: ${{ steps.install.outputs.version }}

  path:
    description: 'The path where ubi was installed'
    value: ${{ steps.install.outputs.path }}

runs:
  using: 'composite'
  steps:
    - name: Install ubi
      id: install
      shell: bash
      run: |
        set -eux -o pipefail

        echo "Installing ubi universal binary installer..."

        # Download and run the bootstrap script
        curl --silent --location \
        https://raw.githubusercontent.com/houseabsolute/ubi/d9348539c2521f05225618139ea23fd3f54bce46/bootstrap/bootstrap-ubi.sh | \
          sh

        # Verify installation
        if command -v ubi >/dev/null 2>&1; then
          UBI_VERSION=$(ubi --version | head -n1 | awk '{print $2}')
          UBI_PATH=$(which ubi)
          echo "✅ ubi ${UBI_VERSION} installed successfully at ${UBI_PATH}"
          echo "version=${UBI_VERSION}" >> $GITHUB_OUTPUT
          echo "path=${UBI_PATH}" >> $GITHUB_OUTPUT
        else
          echo "❌ Failed to install ubi"
          exit 1
        fi

        # Add to PATH for subsequent steps
        echo "$(dirname $(which ubi))" >> $GITHUB_PATH
