---
name: CI
on: [pull_request, workflow_dispatch]

jobs:
  minimal:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install ubi
        uses: ./
        id: ubi
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          projects: |
            oalders/is
            oalders/debounce -v

      - name: Verify installations
        run: |
          is there ubi --verbose
          is there is --verbose
          is there debounce --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  no_sudo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install ubi
        uses: ./
        id: ubi
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Use ubi to install other tools
        run: ubi --project oalders/is --in /home/runner/.local/bin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify installations
        run: |
          is there ubi --verbose
          is there is --verbose
          is known summary var --md >> $GITHUB_STEP_SUMMARY
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  sudo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install ubi
        uses: ./
        id: ubi
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          sudo: true
      - name: Use ubi to install other tools
        run: |
          sudo ubi --project oalders/is --in /usr/local/bin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify installations
        run: |
          echo "ubi version: ${{ steps.ubi.outputs.version }}"
          echo "ubi path: ${{ steps.ubi.outputs.path }}"
          is there ubi --verbose
          is there is --verbose
          sudo is known summary var --md >> $GITHUB_STEP_SUMMARY
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  sudo_with_target:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install ubi
        uses: ./
        id: ubi
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          sudo: true
        env:
          TARGET: /usr/local/sbin
      - name: Use ubi to install other tools
        run: |
          sudo ubi --project oalders/is --in /usr/sbin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify installations
        run: |
          echo "ubi version: ${{ steps.ubi.outputs.version }}"
          echo "ubi path: ${{ steps.ubi.outputs.path }}"
          is there ubi --verbose
          is there is --verbose
  alpine:
    runs-on: ubuntu-latest
    container: alpine:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - run: apk add curl

      - name: Install ubi
        uses: ./
        id: ubi
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          projects: |
            oalders/is -v
            oalders/debounce -v

      - name: Verify installations
        run: |
          is there ubi --verbose
          is there is --verbose
          is there debounce --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
