---
name: CI
on: [pull_request, workflow_dispatch]

jobs:
  sudo:
    runs-on: ubuntu-latest
    steps:
      - name: Install ubi
        uses: oalders/install-ubi-action@v0.0.3
        id: ubi

      - name: Use ubi to install other tools
        run: |
          # Install is using ubi
          sudo ubi --project oalders/is --in /usr/local/bin

      - name: Verify installations
        run: |
          echo "ubi version: ${{ steps.ubi.outputs.version }}"
          echo "ubi path: ${{ steps.ubi.outputs.path }}"
          is --version
          is there ubi --verbose
  no_sudo:
    runs-on: ubuntu-latest
    steps:
      - name: Install ubi
        uses: oalders/install-ubi-action@v0.0.3
        id: ubi

      - name: Use ubi to install other tools
        run: ubi --project oalders/is

      - name: Verify installations
        run: |
          echo "ubi version: ${{ steps.ubi.outputs.version }}"
          is --version
          is there ubi --verbose
